services:
  mysql:
    container_name: kabowd-mysql
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    hostname: ${PS_HOSTNAME:-localhost}
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=latest
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-14.21.3}
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: kabowd-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: adminkabowd
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./modules/ # local path to the modules
        target: /var/www/html/modules/ # path to be mounted in the container
      - type: bind
        source: ./themes/ # local path to the theme
        target: /var/www/html/themes/ # path to be mounted in the container
      #- psdata:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: kabowd-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - prestashop_network
    restart: unless-stopped
    ports:
      - 8081:80

networks:
  prestashop_network:

volumes:
  psdata:
  dbdata:
  vendor:
  var: